Fix nokogiri installation
The error was:
```
ERROR:  Error installing nokogiri:
	The last version of nokogiri (>= 0) to support your Ruby & RubyGems was 1.13.10. Try installing it with `gem install nokogiri -v 1.13.10`
	nokogiri requires Ruby version >= 2.7, < 3.3.dev. The current ruby version is 2.6.6.146.
```